name: build

on:
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - run: |
          go get ./...
          go install github.com/markbates/pkger/cmd/pkger

      - run: go generate ./...

      - run: go build -o dist/app
        env:
          CGO_ENABLED: 0

      - run: docker build -t ghcr.io/trim21/cactbot_importer:latest .
