name: docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20"

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go get ./...

      - run: go build -trimpath -ldflags="-s -w" -o dist/app
        env:
          CGO_ENABLED: 0

      - run: docker build -t ghcr.io/trim21/downloader-prom-exporter:latest .

      - run: |
          echo $DOCKER_TOKEN | docker login ghcr.io -u Trim21 --password-stdin
          docker push ghcr.io/trim21/downloader-prom-exporter:latest
        if: github.event_name == 'push'
        env:
          DOCKER_TOKEN: ${{ github.token }}
