name: docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - run: go get ./...

      - run: go build -trimpath -ldflags="-s -w" -o dist/app
        env:
          CGO_ENABLED: 0

      - run: docker buildx build -t ghcr.io/trim21/downloader-prom-exporter:latest .

      - uses: docker/login-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: docker push ghcr.io/trim21/downloader-prom-exporter:latest
        if: ${{ github.event_name == 'push' }}
